name: Claude Code Review
# Automated AI-powered code reviews for pull requests

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, edited]

permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write

jobs:
  claude-review:
    uses: totetech/.github/.github/workflows/claude-code-review.yml@main
    with:
      skip_large_prs: true
      max_files: 50
      max_lines: 2000
      # custom_prompt: |
      #   Add your custom review prompt here if needed
      #   This will override the default prompt
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}