name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, edited]

jobs:
  claude-review:
    uses: ./workflows/claude-code-review.yml
    with:
      skip_large_prs: true
      max_files: 50
      max_lines: 2000